name: Build

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

env:
  IMAGE_NAME: lancache-bundle

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Build image
        run: docker build . --tag $IMAGE_NAME
      
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/jccit/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest